import Products from '@/components/home/Products';
import React from 'react';

export const metadata = {
  title: "All products",
  description: "Generated by create next app",
};


const ProductsPage = () => {
  return (
    <div>
      <Products></Products>
    </div>
  );
};

export default ProductsPage;